"""
Skill 5: FHIR Action Drafter

Drafts FHIR R4 resources (MedicationRequest + Communication) from an escalation
summary so a clinician can review and submit them with one click. Never
auto-submits, never auto-prescribes.

Every drafted resource is emitted with:
  - status="draft"
  - intent="proposal"
  - a `review_required: true` flag in the response envelope

The tool is deterministic. It does not call an LLM. It takes structured input
from the agent (drug name, alternative, gene, phenotype, CPIC citation, etc.)
and assembles spec-conformant FHIR JSON.
"""
import logging
import uuid
from datetime import datetime, timezone

from google.adk.tools import ToolContext

logger = logging.getLogger(__name__)

CPIC_SYSTEM = "https://cpicpgx.org"
PGX_REASON_SYSTEM = "http://terminology.hl7.org/CodeSystem/reason-medication-not-given"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _patient_ref(patient_id: str) -> dict:
    return {"reference": f"Patient/{patient_id}"} if patient_id else {"display": "Unknown patient"}


def _draft_medication_request(
    patient_id: str,
    alternative_medication: str,
    current_medication: str,
    gene: str,
    phenotype: str,
    cpic_citation: str,
) -> dict:
    """Build a draft MedicationRequest proposing the CPIC alternative."""
    return {
        "resourceType": "MedicationRequest",
        "id": f"draft-{uuid.uuid4()}",
        "status": "draft",
        "intent": "proposal",
        "subject": _patient_ref(patient_id),
        "authoredOn": _now_iso(),
        "medicationCodeableConcept": {
            "text": alternative_medication,
        },
        "reasonCode": [
            {
                "text": (
                    f"Pharmacogenomic alternative to {current_medication}. "
                    f"Patient is {gene} {phenotype}. "
                    f"Per {cpic_citation}, current therapy is expected to be "
                    f"sub-therapeutic or unsafe; this draft proposes an "
                    f"alternative that does not depend on {gene} activation."
                ),
            }
        ],
        "supportingInformation": [
            {
                "display": cpic_citation,
            }
        ],
        "note": [
            {
                "text": (
                    "DRAFT — Generated by Homeward as a clinician decision-support "
                    "proposal. Requires review and explicit approval by the "
                    "prescribing clinician before submission."
                ),
            }
        ],
    }


def _draft_discontinue_request(
    patient_id: str,
    current_medication: str,
    gene: str,
    phenotype: str,
) -> dict:
    """Companion proposal: discontinue the original medication."""
    return {
        "resourceType": "MedicationRequest",
        "id": f"draft-{uuid.uuid4()}",
        "status": "draft",
        "intent": "proposal",
        "subject": _patient_ref(patient_id),
        "authoredOn": _now_iso(),
        "medicationCodeableConcept": {
            "text": current_medication,
        },
        "doNotPerform": True,
        "reasonCode": [
            {
                "coding": [
                    {
                        "system": PGX_REASON_SYSTEM,
                        "code": "patient objection",
                        "display": "Pharmacogenomic contraindication",
                    }
                ],
                "text": (
                    f"Discontinuation proposed: patient is {gene} {phenotype}; "
                    f"{current_medication} is expected to be sub-therapeutic "
                    f"or carry elevated risk."
                ),
            }
        ],
        "note": [
            {
                "text": (
                    "DRAFT — Discontinuation proposal. Requires clinician approval."
                ),
            }
        ],
    }


def _draft_communication(
    patient_id: str,
    recipient: str,
    escalation_level: str,
    clinical_summary: str,
    cpic_citation: str,
) -> dict:
    """Build a draft Communication addressed to the care team."""
    return {
        "resourceType": "Communication",
        "id": f"draft-{uuid.uuid4()}",
        "status": "preparation",
        "category": [
            {
                "text": "Clinician decision support — pharmacogenomic alert",
            }
        ],
        "priority": "routine" if escalation_level == "GREEN" else (
            "urgent" if escalation_level == "AMBER" else "stat"
        ),
        "subject": _patient_ref(patient_id),
        "recipient": [{"display": recipient or "Care team"}],
        "sender": {"display": "Homeward (clinical decision support agent)"},
        "sent": _now_iso(),
        "payload": [
            {
                "contentString": (
                    f"[{escalation_level}] Pharmacogenomic finding for review.\n\n"
                    f"{clinical_summary}\n\n"
                    f"Evidence: {cpic_citation}\n\n"
                    f"Homeward has prepared a draft MedicationRequest with the "
                    f"CPIC-recommended alternative. Please review and approve, "
                    f"modify, or reject before any change is made to the patient's "
                    f"prescription."
                ),
            }
        ],
        "note": [
            {
                "text": "DRAFT — Awaiting clinician review before sending.",
            }
        ],
    }


def draft_clinical_action(
    alternative_medication: str,
    current_medication: str,
    gene: str,
    phenotype: str,
    cpic_citation: str,
    clinical_summary: str,
    escalation_level: str,
    recipient: str,
    tool_context: ToolContext,
) -> dict:
    """
    Drafts FHIR resources a clinician can review and submit.

    Produces (1) a draft MedicationRequest proposing the CPIC alternative,
    (2) a draft MedicationRequest proposing discontinuation of the flagged
    drug, and (3) a draft Communication addressed to the care team. All
    resources are status='draft' / intent='proposal' — never auto-submitted.

    Args:
        alternative_medication: CPIC-recommended alternative drug + dose
            (e.g. 'Oxycodone 5mg every 4-6 hours as needed').
        current_medication: The drug being replaced (e.g. 'Codeine 30mg').
        gene: The pharmacogenomic gene driving the recommendation
            (e.g. 'CYP2D6').
        phenotype: The patient's phenotype for that gene
            (e.g. 'Poor Metabolizer').
        cpic_citation: CPIC guideline reference
            (e.g. 'CPIC Guideline for CYP2D6 and Codeine Therapy (Crews et al., 2021)').
        clinical_summary: Plain-language summary of the finding for the care team.
        escalation_level: 'GREEN', 'AMBER', or 'RED' — sets Communication priority.
        recipient: Display name of the recipient
            (e.g. 'Surgical team — Urology').

    Returns a dict with the draft FHIR resources and a review_required flag.
    """
    patient_id = tool_context.state.get("patient_id", "")
    level = (escalation_level or "AMBER").strip().upper()
    if level not in ("GREEN", "AMBER", "RED"):
        level = "AMBER"

    logger.info(
        "tool_draft_clinical_action patient_id=%s level=%s gene=%s phenotype=%s "
        "current=%s alternative=%s",
        patient_id, level, gene, phenotype, current_medication, alternative_medication,
    )

    proposed_rx = _draft_medication_request(
        patient_id, alternative_medication, current_medication,
        gene, phenotype, cpic_citation,
    )
    discontinue_rx = _draft_discontinue_request(
        patient_id, current_medication, gene, phenotype,
    )
    communication = _draft_communication(
        patient_id, recipient, level, clinical_summary, cpic_citation,
    )

    return {
        "status": "success",
        "patient_id": patient_id,
        "review_required": True,
        "auto_submitted": False,
        "disclaimer": (
            "These FHIR resources are DRAFT proposals generated as clinical "
            "decision support. They are not orders. A licensed clinician must "
            "review, approve, modify, or reject each resource before any "
            "change is made to the patient's record."
        ),
        "draft_resources": {
            "proposed_medication_request": proposed_rx,
            "discontinue_medication_request": discontinue_rx,
            "communication_to_care_team": communication,
        },
        "summary_for_clinician": (
            f"Homeward has drafted {3} FHIR resources for your review: "
            f"a MedicationRequest proposing {alternative_medication} "
            f"(intent=proposal, status=draft), a discontinuation proposal "
            f"for {current_medication}, and a Communication to "
            f"{recipient or 'the care team'}. Each is held in draft state "
            f"and will not be submitted to the EHR until you approve."
        ),
    }
